"""Shared visual design for Novachrono widgets."""

from novachrono.design.components import (
    create_panel,
    draw_centered_text,
    draw_placeholder_header,
    draw_widget_header,
)
from novachrono.design.theme import (
    ACCENT_COLORS,
    BACKGROUND_COLOR,
    CONTENT_LEFT,
    CONTENT_RIGHT,
    CORNER_RADIUS,
    FRAME_ACCENT_COLOR,
    FRAME_DIM_COLOR,
    FRAME_LINE_COLOR,
    HEADER_DIVIDER_Y,
    HEADER_TOP,
    MUTED_TEXT_COLOR,
    OUTER_MARGIN,
    PANEL_COLOR,
    PANEL_COUNT,
    PANEL_SIZE,
    SUBTLE_TEXT_COLOR,
    TEXT_COLOR,
)

__all__ = [
    "ACCENT_COLORS",
    "BACKGROUND_COLOR",
    "CONTENT_LEFT",
    "CONTENT_RIGHT",
    "CORNER_RADIUS",
    "FRAME_ACCENT_COLOR",
    "FRAME_DIM_COLOR",
    "FRAME_LINE_COLOR",
    "HEADER_DIVIDER_Y",
    "HEADER_TOP",
    "MUTED_TEXT_COLOR",
    "OUTER_MARGIN",
    "PANEL_COLOR",
    "PANEL_COUNT",
    "PANEL_SIZE",
    "SUBTLE_TEXT_COLOR",
    "TEXT_COLOR",
    "create_panel",
    "draw_centered_text",
    "draw_placeholder_header",
    "draw_widget_header",
]
