"""Shared visual design for Novachrono widgets."""

from novachrono.design.components import (
    WidgetIconRenderer,
    create_panel,
    draw_centered_text,
    draw_placeholder_header,
    draw_widget_header,
)
from novachrono.design.theme import (
    ACCENT_COLORS,
    BACKGROUND_COLOR,
    BORDER_COLOR,
    CONTENT_LEFT,
    CONTENT_RIGHT,
    CORNER_RADIUS,
    HEADER_DIVIDER_Y,
    HEADER_ICON_LEFT,
    HEADER_ICON_SIZE,
    HEADER_ICON_TOP,
    HEADER_TITLE_X,
    HEADER_TITLE_Y,
    MUTED_TEXT_COLOR,
    OUTER_MARGIN,
    PANEL_COLOR,
    PANEL_COUNT,
    PANEL_SIZE,
    TEXT_COLOR,
)

__all__ = [
    "ACCENT_COLORS",
    "BACKGROUND_COLOR",
    "BORDER_COLOR",
    "CONTENT_LEFT",
    "CONTENT_RIGHT",
    "CORNER_RADIUS",
    "HEADER_DIVIDER_Y",
    "HEADER_ICON_LEFT",
    "HEADER_ICON_SIZE",
    "HEADER_ICON_TOP",
    "HEADER_TITLE_X",
    "HEADER_TITLE_Y",
    "MUTED_TEXT_COLOR",
    "OUTER_MARGIN",
    "PANEL_COLOR",
    "PANEL_COUNT",
    "PANEL_SIZE",
    "TEXT_COLOR",
    "WidgetIconRenderer",
    "create_panel",
    "draw_centered_text",
    "draw_placeholder_header",
    "draw_widget_header",
]
