"""Shared visual design for Novachrono widgets."""

from novachrono.design.components import (
    create_panel,
    draw_centered_text,
    draw_placeholder_header,
    draw_widget_header,
    find_font_that_fits,
    text_width,
)
from novachrono.design.theme import (
    BACKGROUND_COLOR,
    CONTENT_LEFT,
    CONTENT_RIGHT,
    FRAME_ACCENT_COLOR,
    FRAME_BRIGHT_COLOR,
    FRAME_DEEP_COLOR,
    FRAME_DIM_COLOR,
    FRAME_LINE_COLOR,
    HEADER_DIVIDER_Y,
    HEADER_TOP,
    MUTED_TEXT_COLOR,
    PANEL_COLOR,
    PANEL_COUNT,
    PANEL_SIZE,
    SUBTLE_TEXT_COLOR,
    TEXT_COLOR,
    WEATHER_CLOUD_COLOR,
    WEATHER_CLOUD_SHADOW_COLOR,
    WEATHER_RAIN_COLOR,
    WEATHER_SUN_COLOR,
    WEATHER_SUN_RAY_COLOR,
)

__all__ = [
    "BACKGROUND_COLOR",
    "CONTENT_LEFT",
    "CONTENT_RIGHT",
    "FRAME_ACCENT_COLOR",
    "FRAME_BRIGHT_COLOR",
    "FRAME_DEEP_COLOR",
    "FRAME_DIM_COLOR",
    "FRAME_LINE_COLOR",
    "HEADER_DIVIDER_Y",
    "HEADER_TOP",
    "MUTED_TEXT_COLOR",
    "PANEL_COLOR",
    "PANEL_COUNT",
    "PANEL_SIZE",
    "SUBTLE_TEXT_COLOR",
    "TEXT_COLOR",
    "WEATHER_CLOUD_COLOR",
    "WEATHER_CLOUD_SHADOW_COLOR",
    "WEATHER_RAIN_COLOR",
    "WEATHER_SUN_COLOR",
    "WEATHER_SUN_RAY_COLOR",
    "create_panel",
    "draw_centered_text",
    "draw_placeholder_header",
    "draw_widget_header",
    "find_font_that_fits",
    "text_width",
]
