from typing import Final

PANEL_SIZE: Final = 128
PANEL_COUNT: Final = 5

BACKGROUND_COLOR: Final = "#0D0B18"
PANEL_COLOR: Final = "#17132F"
BORDER_COLOR: Final = "#332B53"

TEXT_COLOR: Final = "#FFFFFF"
MUTED_TEXT_COLOR: Final = "#AAA4BA"

ACCENT_COLORS: Final = (
    "#9B7CFF",
    "#42D9FF",
    "#D36BFF",
    "#FFB347",
    "#75E6A4",
)

OUTER_MARGIN: Final = 8
CORNER_RADIUS: Final = 12

CONTENT_LEFT: Final = 16
CONTENT_RIGHT: Final = PANEL_SIZE - 16

HEADER_ICON_LEFT: Final = 14
HEADER_ICON_TOP: Final = 15
HEADER_ICON_SIZE: Final = 18
HEADER_TITLE_X: Final = 40
HEADER_TITLE_Y: Final = 17
HEADER_DIVIDER_Y: Final = 38
