from typing import Final

PANEL_SIZE: Final = 128
PANEL_COUNT: Final = 5

BACKGROUND_COLOR: Final = "#020913"
PANEL_COLOR: Final = "#020B14"

FRAME_LINE_COLOR: Final = "#C9F3FF"
FRAME_ACCENT_COLOR: Final = "#00D7FF"
FRAME_BRIGHT_COLOR: Final = "#72ECFF"
FRAME_DIM_COLOR: Final = "#0B4254"
FRAME_DEEP_COLOR: Final = "#062632"

TEXT_COLOR: Final = "#EAFBFF"
MUTED_TEXT_COLOR: Final = "#9AD7E6"
SUBTLE_TEXT_COLOR: Final = "#66AABD"

WEATHER_SUN_COLOR: Final = "#FFD447"
WEATHER_SUN_RAY_COLOR: Final = "#FFB703"
WEATHER_CLOUD_COLOR: Final = "#F4F8FA"
WEATHER_CLOUD_SHADOW_COLOR: Final = "#9DB8C4"
WEATHER_RAIN_COLOR: Final = "#29B6F6"

CONTENT_LEFT: Final = 16
CONTENT_RIGHT: Final = PANEL_SIZE - 16

HEADER_TOP: Final = 18
HEADER_DIVIDER_Y: Final = 30
