from typing import Final

PANEL_SIZE: Final = 128
PANEL_COUNT: Final = 5

BACKGROUND_COLOR: Final = "#020913"
PANEL_COLOR: Final = "#020B14"

FRAME_LINE_COLOR: Final = "#C9F3FF"
FRAME_ACCENT_COLOR: Final = "#00D7FF"
FRAME_DIM_COLOR: Final = "#0B4254"

TEXT_COLOR: Final = "#EAFBFF"
MUTED_TEXT_COLOR: Final = "#9AD7E6"
SUBTLE_TEXT_COLOR: Final = "#66AABD"

ACCENT_COLORS: Final = (
    "#00D7FF",
    "#00D7FF",
    "#00D7FF",
    "#00D7FF",
    "#00D7FF",
)

OUTER_MARGIN: Final = 8
CORNER_RADIUS: Final = 12

CONTENT_LEFT: Final = 16
CONTENT_RIGHT: Final = PANEL_SIZE - 16

HEADER_TOP: Final = 11
HEADER_DIVIDER_Y: Final = 24
